This video is for fun only. This is not a serious mathematic video.
The mathematic concepts mentioned in the video might not be rigorous enough. Please be careful with it.

*Inspired by*:
- Reading comprehension article A on the exam paper in video `BV1aV411N7kF`
- The "Becoming Human" video series by `@Sheepherd_Wagner`

*Special Thanks to*: 
- The JAnim animation engine and its developer, `@jkjkil-jiang`
- Illustrations are adopted from SVG Repo (`svgrepo.com`)
- Voice generated by TTS Maker (`ttsmaker.com`)